kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: node
    commands:
      - npm install
      - npm run build

  - name: gitea_release
    image: plugins/gitea-release
    settings:
      api_key:
        from_secret: CI_REGISTRY_API_KEY
      base_url: https://git.legendary-drop.de
      files: artifacts/*
      checksum:
        - md5
        - sha1
        - sha256
        - sha512
        - adler32
        - crc32
    when:
      event: tag
